version: '3.5'

services:
  app:
    container_name: creativestyle
    build:
      context: .  
      dockerfile: Dockerfile
    volumes:
      - .:/app

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  db:
    image: postgres:latest
    container_name: postgresql-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: creativestyle
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresql-db
    ports:
      - "5432:5432"
    volumes:
      - .:/app