controllers:
    resource:
        path: ../src/Infrastructure/UI/Controller/
        namespace: App\Infrastructure\UI\Controller
    type: attribute
index:
    path: /
    controller: App\Infrastructure\UI\Controller\SalesController::listProducts
