services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Infrastructure\Service\Discount\EveryFifthProductFreeDiscountPolicy: ~
    App\Infrastructure\Service\Discount\PercentageDiscountPolicy: ~

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Service\Sales\CartPriceCalculator:
        arguments:
            $discountPolicies:
                - '@App\Infrastructure\Service\Discount\EveryFifthProductFreeDiscountPolicy'
                - '@App\Infrastructure\Service\Discount\PercentageDiscountPolicy'